# There is no 'config', 'version', or 'name' block at all.
# The file starts directly with 'binds'.

binds:
  - port: 3000
    listeners:
      - name: default
        protocol: HTTP
        routes:
          # Route 1: For the HTTP Backend
          - name: mcp-http-route
            match:
              path: "/http-mcp"
            backends:
              - mcp:
                  targets:
                    - name: topcoder-mcp-http
                      mcp:
                        host: http://localhost:3005/

          # Route 2: For the HTTPS Backend
          - name: mcp-https-route
            match:
              path: "/https-mcp"
            backends:
              - mcp:
                  targets:
                    - name: topcoder-mcp-https
                      mcp:
                        host: https://localhost:3443/
            policies:
              backendTLS:
                root: ./scenario1/certs/cert.pem