config: # <-- Add this top-level section
  version: "1.0"
  name: "mcp-multi-backend-demo"

binds: # <-- 'binds' should be at the same level as 'config'
  - port: 3000
    listeners:
      - name: default
        protocol: HTTP
        routes:
          # Route 1: For the HTTP Backend
          - name: mcp-http-route
            match:
              path: "/http-mcp" # Visitors asking for "/http-mcp" go here
            backends:
              - mcp:
                  targets:
                    - name: topcoder-mcp-http
                      mcp:
                        host: http://localhost:3005/
                        
          # Route 2: For the HTTPS Backend
          - name: mcp-https-route
            match:
              path: "/https-mcp" # Visitors asking for "/https-mcp" go here
            backends:
              - mcp:
                  targets:
                    - name: topcoder-mcp-https
                      mcp:
                        host: https://localhost:3443/
            policies:
              backendTLS:
                # Tell AgentGateway to trust our self-signed certificate
                root: ./scenario1/certs/cert.pem