# FILE: configs/mcp/mcp-multi-backend.yaml

binds:
  - port: 3000
    listeners:
      - name: default
        protocol: HTTP
        routes:
          # Route 1: For the HTTP Backend
          - name: mcp-http-route
            matches:
              - path:
                  pathPrefix: "/http-mcp"
            backends:
              - http: # <-- USE 'http' for a simple HTTP backend
                  targets:
                    - name: simple-http-backend
                      http: # <-- USE 'http'
                        host: http://localhost:3005/

          # Route 2: For the HTTPS Backend
          - name: mcp-https-route
            matches:
              - path:
                  pathPrefix: "/https-mcp"
            backends:
              - http: # <-- USE 'http' for a simple HTTPS backend
                  targets:
                    - name: simple-https-backend
                      http: # <-- USE 'http'
                        host: https://localhost:3443/
            policies:
              backendTLS:
                root: ./scenario1/certs/cert.pem